version: '3.8'
services:
  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: rootpass
      MARIADB_DATABASE: zappydb
      MARIADB_USER: zappyuser
      MARIADB_PASSWORD: zappypass
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  backend:
    build:
      context: ./zappy-kiwify-server
      dockerfile: Dockerfile
    restart: always
    environment:
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_USER: zappyuser
      DB_PASSWORD: zappypass
      DB_NAME: zappydb
    ports:
      - "3001:3001"
    depends_on:
      - mariadb

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://backend:3001
      NEXT_PUBLIC_WS_URL: http://backend:3001
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mariadb_data:
